7 commit

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -56,6 +56,18 @@ jobs:
         username: ${{ secrets.EC2_USERNAME }}
         key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
         script: |
+          sudo apt-get update
+
+          sudo apt-get install -y awscli
+
+          echo "Logging in to ECR..."
+          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 265697931443.dkr.ecr.us-east-1.amazonaws.com
+
+          if [ $? -ne 0 ]; then
+            echo "ECR login failed!"
+            exit 1
+          fi
+
           docker pull 265697931443.dkr.ecr.us-east-1.amazonaws.com/test/repo:latest
 
           docker stop my-nginx-container || true
